name: Build HTML documentation

on: [push, pull_request]

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10"

      - name: Install Pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc

      - name: Install documentation dependencies
        run: |
          python -mpip install -r doc/requirements.txt

      - name: Install qutip-qoc from GitHub
        run: |
          python -mpip install -e .[full]
          # Install in editable mode so it doesn't matter if we import from
          # inside the installation directory, otherwise we can get some errors
          # because we're importing from the wrong location.
          python -c 'import qutip_qoc; print("QuTiP qoc Version:      %s" % qutip_qoc.__version__)'
          python -c 'import qutip; qutip.about()'

      - name: Build documentation
        working-directory: doc
        run: |
          make html SPHINXOPTS="--keep-going -T"
          # Above flags are:
          #   --keep-going : do not stop after the first error
          #   -T : display a full traceback if a Python exception occurs

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: qutip_qoc_html_docs
          path: doc/_build/html/*
          if-no-files-found: error
