name: Build wheels, optionally deploy to PyPI

on:
  workflow_dispatch:
    inputs:
      confirm_ref:
        description: "Confirm chosen branch name to deploy to PyPI (optional):"
        default: ""
      override_version:
        description: "Override version number (optional):"
        default: ""

jobs:
  build:
    name: Build distribution 📦
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    env:
      # Set up wheels matrix.  This is CPython 3.10--3.14 for all OS targets.
      CIBW_BUILD: "cp3{10,11,12,13,14}-*"
      # Numpy and SciPy do not supply wheels for i686 or win32 for
      # Python 3.10+, so we skip those:
      CIBW_SKIP: "*-musllinux* *-manylinux_i686 *-win32"
      # Force recent version of manylinux
      # manylinux2014 no longer supported by scipy and numpy
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install cibuildwheel
        run: >-
          python3 -m
          pip install
          cibuildwheel
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m cibuildwheel --output-dir dist
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions-${{ matrix.os }}
          path: dist/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: ${{ github.event.inputs.confirm_ref != '' && github.event.inputs.confirm_ref != 'test' }}
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/qutip-qoc
    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          pattern: python-package-distributions-*
          path: dist/
          merge-multiple: true
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
