name: Build wheels, optionally deploy to PyPI

on:
  workflow_dispatch:
    inputs:
      confirm_ref:
        description: "Confirm chosen branch name to deploy to PyPI (optional):"
        default: ""

      override_version:
        description: "Override version number (optional):"
        default: ""

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build distribution 📦
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    env:
      # Build wheels for supported CPython versions.
      CIBW_BUILD: "cp3{11,12,13,14}-*"

      # NumPy and SciPy do not supply wheels for these targets.
      CIBW_SKIP: "*-musllinux* *-manylinux_i686 *-win32"

      # manylinux2014 no longer supported by scipy/numpy
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install "cibuildwheel>=2.20,<3"

      - name: Build binary wheels and source tarball
        run: |
          python -m cibuildwheel --output-dir dist

      - name: Store distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions-${{ matrix.os }}
          path: dist/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI

    if: ${{ github.event.inputs.confirm_ref != '' && github.event.inputs.confirm_ref != 'test' }}

    needs:
      - build

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/qutip-qoc

    permissions:
      id-token: write

    steps:
      - name: Download all distributions
        uses: actions/download-artifact@v5
        with:
          pattern: python-package-distributions-*
          path: dist/
          merge-multiple: true

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
